/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* mav_nmpc_tracker_model_expl_ode_fun:(i0[12],i1[4],i2[0])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][8] */
  w0 = arg[0] ? arg[0][8] : 0;
  /* #7: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #8: @2 = input[0][7] */
  w2 = arg[0] ? arg[0][7] : 0;
  /* #9: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #10: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #11: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #12: @5 = input[0][6] */
  w5 = arg[0] ? arg[0][6] : 0;
  /* #13: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #14: @7 = (@2*@6) */
  w7  = (w2*w6);
  /* #15: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #16: @7 = (@7*@0) */
  w7 *= w0;
  /* #17: @4 = (@4+@7) */
  w4 += w7;
  /* #18: @7 = input[1][0] */
  w7 = arg[1] ? arg[1][0] : 0;
  /* #19: @4 = (@4*@7) */
  w4 *= w7;
  /* #20: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #21: @0 = (@0*@3) */
  w0 *= w3;
  /* #22: @1 = (@1*@2) */
  w1 *= w2;
  /* #23: @1 = (@1*@6) */
  w1 *= w6;
  /* #24: @0 = (@0-@1) */
  w0 -= w1;
  /* #25: @0 = (@0*@7) */
  w0 *= w7;
  /* #26: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #27: @0 = -9.81 */
  w0 = -9.8100000000000005e+00;
  /* #28: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #29: @2 = (@2*@5) */
  w2 *= w5;
  /* #30: @2 = (@2*@7) */
  w2 *= w7;
  /* #31: @0 = (@0+@2) */
  w0 += w2;
  /* #32: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #33: @0 = input[0][9] */
  w0 = arg[0] ? arg[0][9] : 0;
  /* #34: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #35: @2 = input[0][10] */
  w2 = arg[0] ? arg[0][10] : 0;
  /* #36: output[0][7] = @2 */
  if (res[0]) res[0][7] = w2;
  /* #37: @7 = input[0][11] */
  w7 = arg[0] ? arg[0][11] : 0;
  /* #38: output[0][8] = @7 */
  if (res[0]) res[0][8] = w7;
  /* #39: @5 = 1.46e-05 */
  w5 = 1.4600000000000001e-05;
  /* #40: @5 = (@5*@2) */
  w5 *= w2;
  /* #41: @5 = (@5*@7) */
  w5 *= w7;
  /* #42: @2 = 1.43e-05 */
  w2 = 1.4300000000000000e-05;
  /* #43: @5 = (@5/@2) */
  w5 /= w2;
  /* #44: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #45: @1 = (@1/@2) */
  w1 /= w2;
  /* #46: @5 = (@5+@1) */
  w5 += w1;
  /* #47: output[0][9] = @5 */
  if (res[0]) res[0][9] = w5;
  /* #48: @5 = -1.46e-05 */
  w5 = -1.4600000000000001e-05;
  /* #49: @5 = (@5*@0) */
  w5 *= w0;
  /* #50: @5 = (@5*@7) */
  w5 *= w7;
  /* #51: @5 = (@5/@2) */
  w5 /= w2;
  /* #52: @7 = input[1][2] */
  w7 = arg[1] ? arg[1][2] : 0;
  /* #53: @7 = (@7/@2) */
  w7 /= w2;
  /* #54: @5 = (@5+@7) */
  w5 += w7;
  /* #55: output[0][10] = @5 */
  if (res[0]) res[0][10] = w5;
  /* #56: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #57: @7 = 2.89e-05 */
  w7 = 2.8900000000000001e-05;
  /* #58: @5 = (@5/@7) */
  w5 /= w7;
  /* #59: output[0][11] = @5 */
  if (res[0]) res[0][11] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 8*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
