/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[17] = 
  {16, 1, 0, 13, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* mav_nmpc_tracker_model_expl_vde_adj:(i0[12],i1[12],i2[4],i3[0])->(o0[16x1,13nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w01, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  const casadi_real *wr00;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  w04 = wr00[3];
  w05 = wr00[4];
  w06 = wr00[5];
  w07 = wr00[6];
  w08 = wr00[7];
  w09 = wr00[8];
  w10 = wr00[9];
  w11 = wr00[10];
  w12 = wr00[11];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][6] */
  w03 = arg[0] ? arg[0][6] : 0;
  /* #6: @2 = cos(@3) */
  w02 = cos( w03 );
  /* #7: @1 = input[0][8] */
  w01 = arg[0] ? arg[0][8] : 0;
  /* #8: @13 = cos(@1) */
  w13 = cos( w01 );
  /* #9: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #10: @15 = cos(@14) */
  w15 = cos( w14 );
  /* #11: @16 = (@13*@15) */
  w16  = (w13*w15);
  /* #12: @17 = input[2][0] */
  w17 = arg[2] ? arg[2][0] : 0;
  /* #13: @18 = (@17*@5) */
  w18  = (w17*w05);
  /* #14: @19 = (@16*@18) */
  w19  = (w16*w18);
  /* #15: @19 = (@2*@19) */
  w19  = (w02*w19);
  /* #16: @19 = (-@19) */
  w19 = (- w19 );
  /* #17: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #18: @20 = (@17*@6) */
  w20  = (w17*w06);
  /* #19: @21 = (@15*@20) */
  w21  = (w15*w20);
  /* #20: @21 = (@3*@21) */
  w21  = (w03*w21);
  /* #21: @19 = (@19-@21) */
  w19 -= w21;
  /* #22: @1 = sin(@1) */
  w01 = sin( w01 );
  /* #23: @17 = (@17*@4) */
  w17 *= w04;
  /* #24: @21 = (@1*@17) */
  w21  = (w01*w17);
  /* #25: @22 = (@15*@21) */
  w22  = (w15*w21);
  /* #26: @22 = (@2*@22) */
  w22  = (w02*w22);
  /* #27: @19 = (@19+@22) */
  w19 += w22;
  /* #28: output[0][3] = @19 */
  if (res[0]) res[0][3] = w19;
  /* #29: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #30: @19 = (@3*@18) */
  w19  = (w03*w18);
  /* #31: @22 = (@13*@19) */
  w22  = (w13*w19);
  /* #32: @22 = (@14*@22) */
  w22  = (w14*w22);
  /* #33: @20 = (@2*@20) */
  w20  = (w02*w20);
  /* #34: @20 = (@14*@20) */
  w20  = (w14*w20);
  /* #35: @22 = (@22-@20) */
  w22 -= w20;
  /* #36: @20 = (@1*@18) */
  w20  = (w01*w18);
  /* #37: @20 = (@15*@20) */
  w20  = (w15*w20);
  /* #38: @22 = (@22+@20) */
  w22 += w20;
  /* #39: @21 = (@3*@21) */
  w21  = (w03*w21);
  /* #40: @21 = (@14*@21) */
  w21  = (w14*w21);
  /* #41: @22 = (@22-@21) */
  w22 -= w21;
  /* #42: @21 = (@13*@17) */
  w21  = (w13*w17);
  /* #43: @21 = (@15*@21) */
  w21  = (w15*w21);
  /* #44: @22 = (@22+@21) */
  w22 += w21;
  /* #45: output[0][4] = @22 */
  if (res[0]) res[0][4] = w22;
  /* #46: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #47: @19 = (@1*@19) */
  w19  = (w01*w19);
  /* #48: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #49: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #50: @19 = (@19+@18) */
  w19 += w18;
  /* #51: @18 = (@15*@3) */
  w18  = (w15*w03);
  /* #52: @22 = (@18*@17) */
  w22  = (w18*w17);
  /* #53: @22 = (@13*@22) */
  w22  = (w13*w22);
  /* #54: @19 = (@19+@22) */
  w19 += w22;
  /* #55: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #56: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #57: @19 = (@19-@17) */
  w19 -= w17;
  /* #58: output[0][5] = @19 */
  if (res[0]) res[0][5] = w19;
  /* #59: @19 = -1.46e-05 */
  w19 = -1.4600000000000001e-05;
  /* #60: @17 = input[0][11] */
  w17 = arg[0] ? arg[0][11] : 0;
  /* #61: @22 = 69930.1 */
  w22 = 6.9930069930069934e+04;
  /* #62: @11 = (@22*@11) */
  w11  = (w22*w11);
  /* #63: @21 = (@17*@11) */
  w21  = (w17*w11);
  /* #64: @21 = (@19*@21) */
  w21  = (w19*w21);
  /* #65: @21 = (@21+@7) */
  w21 += w07;
  /* #66: output[0][6] = @21 */
  if (res[0]) res[0][6] = w21;
  /* #67: @21 = 1.46e-05 */
  w21 = 1.4600000000000001e-05;
  /* #68: @22 = (@22*@10) */
  w22 *= w10;
  /* #69: @17 = (@17*@22) */
  w17 *= w22;
  /* #70: @17 = (@21*@17) */
  w17  = (w21*w17);
  /* #71: @17 = (@17+@8) */
  w17 += w08;
  /* #72: output[0][7] = @17 */
  if (res[0]) res[0][7] = w17;
  /* #73: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #74: @19 = (@19*@17) */
  w19 *= w17;
  /* #75: @19 = (@19*@11) */
  w19 *= w11;
  /* #76: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #77: @21 = (@21*@17) */
  w21 *= w17;
  /* #78: @21 = (@21*@22) */
  w21 *= w22;
  /* #79: @19 = (@19+@21) */
  w19 += w21;
  /* #80: @19 = (@19+@9) */
  w19 += w09;
  /* #81: output[0][8] = @19 */
  if (res[0]) res[0][8] = w19;
  /* #82: @15 = (@15*@2) */
  w15 *= w02;
  /* #83: @15 = (@15*@6) */
  w15 *= w06;
  /* #84: @6 = (@1*@14) */
  w06  = (w01*w14);
  /* #85: @16 = (@16*@3) */
  w16 *= w03;
  /* #86: @6 = (@6-@16) */
  w06 -= w16;
  /* #87: @6 = (@6*@5) */
  w06 *= w05;
  /* #88: @15 = (@15+@6) */
  w15 += w06;
  /* #89: @13 = (@13*@14) */
  w13 *= w14;
  /* #90: @18 = (@18*@1) */
  w18 *= w01;
  /* #91: @13 = (@13+@18) */
  w13 += w18;
  /* #92: @13 = (@13*@4) */
  w13 *= w04;
  /* #93: @15 = (@15+@13) */
  w15 += w13;
  /* #94: output[0][9] = @15 */
  if (res[0]) res[0][9] = w15;
  /* #95: output[0][10] = @22 */
  if (res[0]) res[0][10] = w22;
  /* #96: output[0][11] = @11 */
  if (res[0]) res[0][11] = w11;
  /* #97: @11 = 34602.1 */
  w11 = 3.4602076124567473e+04;
  /* #98: @11 = (@11*@12) */
  w11 *= w12;
  /* #99: output[0][12] = @11 */
  if (res[0]) res[0][12] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 34;
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 34*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
